packages:
  - apps/*
  - packages/*
  - jobs

overrides:
  esbuild: ">=0.25.0"
  postcss: ">=8.5.23"
  sharp: ">=0.35.0"

allowBuilds:
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
